### ISSUE TITLE
Installation of SmartCLIDE

### ISSUE THREAD

**Issue by phkrief** [eclipse-researchlabs/smartclide-docs#3]
Do we plan to create documentation explaining how to install SmartCLIDE on top of Theia?
Thx

**Comment by deanone** [comment]
Dear @phkrief ,

Yes, we do. That would be in the "For the sysadmin" page here:

https://eclipse-researchlabs.github.io/smartclide-docs/getting-started-sysadmin/

If you want to make any additions to it, just create a PR, assign it to me for review, and I will merge it.
